export const questions = [
  // ------------------------------------------------------
  // STEM (15 questions per difficulty)
  // EASY
  { question: "What is the square root of 144?", 
    options: ["10", "12", "14", "16"], 
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "What planet is known as the Red Planet?", 
    options: ["Mars", "Venus", "Jupiter", "Saturn"], 
    correctIndex: 0, category: "stem", difficulty: "easy" },
  { question: "What is H2O commonly known as?", 
    options: ["Hydrogen Peroxide", "Water", "Oxygen", "Salt"], 
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "Which number is a prime number?", 
    options: ["15", "21", "17", "27"], 
    correctIndex: 2, category: "stem", difficulty: "easy" },
  { question: "What is the chemical symbol for gold?", 
    options: ["Au", "Ag", "Gd", "Go"], 
    correctIndex: 0, category: "stem", difficulty: "easy" },
  { question: "What is 0! (zero factorial)?", 
    options: ["0", "1", "Undefined", "Infinity"], 
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "Which gas do plants absorb from the atmosphere?", 
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], 
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "What force keeps planets in orbit around the sun?", 
    options: ["Magnetism", "Gravity", "Friction", "Centrifugal"], 
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "Who developed the theory of relativity?", 
    options: ["Newton", "Tesla", "Einstein", "Galileo"], 
    correctIndex: 2, category: "stem", difficulty: "easy" },
  { question: "How many sides does a hexagon have?",
    options: ["5", "6", "7", "8"],
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "How many planets are in our solar system?",
    options: ["7", "8", "9", "10"],
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "What is the center of an atom called?",
    options: ["Electron", "Nucleus", "Proton", "Liver"],
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Cytoplasm", "Cell Membrane", "Mitochondria"],
    correctIndex: 3, category: "stem", difficulty: "easy" },
  { question: "What is the largest planet in our solar system?",
    options: ["Jupiter", "Uranus", "Saturn", "Pluto"],
    correctIndex: 0, category: "stem", difficulty: "easy" },
  { question: "How many degrees are in a right angle?",
    options: ["30", "50", "80", "90"],
    correctIndex: 3, category: "stem", difficulty: "easy" },

  // MEDIUM
  { question: "How many bones are in the human body?", 
    options: [ "210","206", "195", "220"], 
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "Which data structure follows FIFO?",
    options: ["Stack", "Queue", "Tree", "Graph"],
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "The process of converting sensitive or complex data into smaller, manageable, or non-sensitive units is called?", 
    options: ["Encryption", "Tokenization", "Hashing", "Anonymization"], 
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "Which organ in the human body produces insulin?", 
    options: ["Liver", "Pancreas", "Kidney", "Stomach"], 
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "Which programming language is known for its use in data science and machine learning?", 
    options: ["Java", "C++", "Python", "Ruby"], 
    correctIndex: 2, category: "stem", difficulty: "medium" },
  { question: "What is the chemical formula for table salt?", 
    options: ["NaCl", "KCl", "NaHCO3", "CaCl2"], 
    correctIndex: 0, category: "stem", difficulty: "medium" },
  { question: "What is Amazon's cloud computing platform called?", 
    options: ["AWS", "Google Cloud", "Azure", "IBM Cloud"], 
    correctIndex: 0, category: "stem", difficulty: "medium" },
  { question: "What does HTTP stand for?",
    options: ["High Tech Transfer Process", "Hyper Transfer Text Program", "Host Text Transfer Protocol", "HyperText Transfer Protocol"],
    correctIndex: 3, category: "stem", difficulty: "medium" },
  { question: "In what base does a binary number system operate?",
    options: ["Base 8", "Base 10", "Base 2", "Base 16"],
    correctIndex: 2, category: "stem", difficulty: "medium" },
  { question: "What is the largest desert in the world?",
    options: ["Sahara", "Kalahari", "Antarctica", "Mojave"],
    correctIndex: 2, category: "stem", difficulty: "medium" },
  { question: "What is the most abundant gas in the universe?",
    options: ["Hydrogen", "Nitrogen", "Oxygen", "Helium"],
    correctIndex: 0, category: "stem", difficulty: "medium" },
  { question: "What part of the human body is primarily responsible for filtering blood?",
    options: ["Liver", "Kidneys", "Heart", "Veins"],
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "What is the term for a substance with a pH less than 7?",
    options: ["Dry", "Neutral", "Acidic", "Alkaline"],
    correctIndex: 2, category: "stem", difficulty: "medium" },
  { question: "Who is known as the first computer programmer?",
    options: ["Ada Lovelace", "Bill Gates", "Konrad Zuse", "Charles Babbage"],
    correctIndex: 0, category: "stem", difficulty: "medium" },
  { question: "What is the next number in the Fibonacci sequence: 1, 1, 2, 3, 5, 8, __?",
    options: ["11", "13", "15", "18"],
    correctIndex: 1, category: "stem", difficulty: "medium" },

  // HARD
  { question: "What is the smallest element on the periodic table by atomic number?", 
    options: ["Natrium", "Lithium", "Beryllium", "Hydrogen"], 
    correctIndex: 3, category: "stem", difficulty: "hard" },
  { question: "Researchers from which company helped develop the first successful quantum computer?",
    options: ["Google", "Salesforce", "D-Wave", "IBM"], 
    correctIndex: 3, category: "stem", difficulty: "hard" },
  { question: "What is Microsoft's analytics platform called?", 
    options: ["Fabric", "Tableau", "Azure", "Office 365"], 
    correctIndex: 0, category: "stem", difficulty: "hard" },
  { question: "Which element is a noble gas?", 
    options: ["Helium", "Oxygen", "Nitrogen", "Carbon"], 
    correctIndex: 0, category: "stem", difficulty: "hard" },
  { question: "What is the time complexity of binary search?",
    options: ["O(n)", "O(n²)", "O(log n)", "O(1)"],
    correctIndex: 2, category: "stem", difficulty: "hard" },
  { question: "Which protocol is used to assign IP addresses automatically on a network?",
    options: ["DNS", "FTP", "DHCP", "SSH"],
    correctIndex: 2, category: "stem", difficulty: "hard" },
  { question: "What is the atomic number of carbon?",
    options: ["4", "6", "8", "12"],
    correctIndex: 1, category: "stem", difficulty: "hard" },
  { question: "What is the name of the process by which a cell divides into two identical daughter cells?",
    options: ["Meiosis", "Mitosis", "Fission", "Budding"],
    correctIndex: 1, category: "stem", difficulty: "hard" },
  { question: "What element did Joseph Priestly discover in 1774?",
    options: ["Nitrogen", "Helium", "Argon", "Oxygen"],
    correctIndex: 3, category: "stem", difficulty: "hard" },
  { question: "What is the pH of water?",
    options: ["5", "6", "7", "8"],
    correctIndex: 2, category: "stem", difficulty: "hard" },
  { question: "At what temperature are Celsius and Fahrenheit equal?",
    options: ["-80 degrees", "-60 degrees", "-40 degrees", "-20 degrees"],
    correctIndex: 2, category: "stem", difficulty: "hard" },
  { question: "What element was named after the Greek word for greenish-yellow?",
    options: ["Chlorine", "Sulfur", "Fluorine", "Uranium"],
    correctIndex: 0, category: "stem", difficulty: "hard" },
  { question: "What letter is used to express the speed of light in E=MC^2?",
    options: ["M", "C", "E", "A"],
    correctIndex: 1, category: "stem", difficulty: "hard" },
  { question: "What type of symmetry can be found in Starfish, whose limbs radiate from one central point?",
    options: ["Radial", "Rotational", "Reflectional", "Bilateral"],
    correctIndex: 0, category: "stem", difficulty: "hard" },
  { question: "Which famous Greek mathematician is known for having accurately calculated the circumference of planet Earth using only shadows and some simple geometry?",
    options: ["Thales", "Euclid", "Eratosthenes", "Archimedes"],
    correctIndex: 2, category: "stem", difficulty: "hard" },

  // ------------------------------------------------------
  // Shows and Movies (15 questions per difficulty)
  // EASY



  
];